version: "3.8"
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - custom

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - custom

volumes:
  dbdata6:

networks:
  custom:
    driver: bridge
